apiDir: ../ticket-rest-api/src/main/java
apiPackagePath: ticket.rest
application:
    baseURI: /ticket-rest
    className: TicketRestApplication
    name: TicketRest
author: me
clientDir: ../ticket-rest-client/src/main/java
forcePredictableContentApplicationXML: false
javaEEPackage: jakarta
testDir: ../ticket-rest-test/src/testIntegration/java