info:
    description: "TicketRest REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "TicketRest"
    version: v1.0
openapi: 3.0.1

components:
    schemas:
        Ticket:
            properties:
                ticketId:
                    format: int64
                    type: integer
                title:
                    type: string
                description:
                    type: string
                category:
                    type: string
                priority:
                    type: string
                status:
                    type: string
                assignedToUserId:
                    format: int64
                    type: integer
            type: object

        TicketCreate:
            properties:
                title:
                    type: string
                description:
                    type: string
                category:
                    type: string
                priority:
                    type: string
                assignedToUserId:
                    format: int64
                    type: integer
            type: object

paths:
    /tickets:
        get:
            operationId: getTickets
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Ticket"
                                type: array
                    description: "Tickets retrieved successfully"

    /tickets/{ticketId}:
        get:
            operationId: getTicket
            parameters:
                - in: path
                  name: ticketId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Ticket"
                    description: "Ticket retrieved successfully"

    /tickets/by-assignee/{assignedToUserId}:
        get:
            operationId: getTicketsByAssignedToUserId
            parameters:
                - in: path
                  name: assignedToUserId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Ticket"
                                type: array
                    description: "Tickets assigned to the user retrieved successfully"

    /sites/{siteId}/tickets:
        post:
            operationId: postSiteTicket
            parameters:
                - in: path
                  name: siteId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/TicketCreate"
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Ticket"
                    description: "Ticket created successfully"