/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ticket.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Ticket service. Represents a row in the &quot;TICKET_Ticket&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ticket.model.impl.TicketModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ticket.model.impl.TicketImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Ticket
 * @generated
 */
@ProviderType
public interface TicketModel
	extends BaseModel<Ticket>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ticket model instance should use the {@link Ticket} interface instead.
	 */

	/**
	 * Returns the primary key of this ticket.
	 *
	 * @return the primary key of this ticket
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ticket.
	 *
	 * @param primaryKey the primary key of this ticket
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this ticket.
	 *
	 * @return the uuid of this ticket
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this ticket.
	 *
	 * @param uuid the uuid of this ticket
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ticket ID of this ticket.
	 *
	 * @return the ticket ID of this ticket
	 */
	public long getTicketId();

	/**
	 * Sets the ticket ID of this ticket.
	 *
	 * @param ticketId the ticket ID of this ticket
	 */
	public void setTicketId(long ticketId);

	/**
	 * Returns the group ID of this ticket.
	 *
	 * @return the group ID of this ticket
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this ticket.
	 *
	 * @param groupId the group ID of this ticket
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this ticket.
	 *
	 * @return the company ID of this ticket
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ticket.
	 *
	 * @param companyId the company ID of this ticket
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ticket.
	 *
	 * @return the user ID of this ticket
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this ticket.
	 *
	 * @param userId the user ID of this ticket
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ticket.
	 *
	 * @return the user uuid of this ticket
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ticket.
	 *
	 * @param userUuid the user uuid of this ticket
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this ticket.
	 *
	 * @return the user name of this ticket
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this ticket.
	 *
	 * @param userName the user name of this ticket
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this ticket.
	 *
	 * @return the create date of this ticket
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this ticket.
	 *
	 * @param createDate the create date of this ticket
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ticket.
	 *
	 * @return the modified date of this ticket
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ticket.
	 *
	 * @param modifiedDate the modified date of this ticket
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this ticket.
	 *
	 * @return the title of this ticket
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this ticket.
	 *
	 * @param title the title of this ticket
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this ticket.
	 *
	 * @return the description of this ticket
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this ticket.
	 *
	 * @param description the description of this ticket
	 */
	public void setDescription(String description);

	/**
	 * Returns the category of this ticket.
	 *
	 * @return the category of this ticket
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this ticket.
	 *
	 * @param category the category of this ticket
	 */
	public void setCategory(String category);

	/**
	 * Returns the priority of this ticket.
	 *
	 * @return the priority of this ticket
	 */
	@AutoEscape
	public String getPriority();

	/**
	 * Sets the priority of this ticket.
	 *
	 * @param priority the priority of this ticket
	 */
	public void setPriority(String priority);

	/**
	 * Returns the status of this ticket.
	 *
	 * @return the status of this ticket
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this ticket.
	 *
	 * @param status the status of this ticket
	 */
	public void setStatus(String status);

	/**
	 * Returns the assigned to user ID of this ticket.
	 *
	 * @return the assigned to user ID of this ticket
	 */
	public long getAssignedToUserId();

	/**
	 * Sets the assigned to user ID of this ticket.
	 *
	 * @param assignedToUserId the assigned to user ID of this ticket
	 */
	public void setAssignedToUserId(long assignedToUserId);

	/**
	 * Returns the assigned to user uuid of this ticket.
	 *
	 * @return the assigned to user uuid of this ticket
	 */
	public String getAssignedToUserUuid();

	/**
	 * Sets the assigned to user uuid of this ticket.
	 *
	 * @param assignedToUserUuid the assigned to user uuid of this ticket
	 */
	public void setAssignedToUserUuid(String assignedToUserUuid);

	@Override
	public Ticket cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:883989358