#
# This is a generated file.
#

api.version=v1.0
batch.engine.entity.class.name=ticket.rest.dto.v1_0.Ticket
batch.engine.task.item.delegate=true
batch.planner.export.enabled=false
batch.planner.import.enabled=true
entity.class.name=ticket.rest.dto.v1_0.Ticket
osgi.jaxrs.application.select=(osgi.jaxrs.name=TicketRest)
osgi.jaxrs.resource=true