 /**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ticket.model.impl;

import ticket.model.Ticket;

import ticket.service.TicketLocalServiceUtil;

/**
 * The extended model base implementation for the Ticket service. Represents a row in the &quot;TICKET_Ticket&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TicketImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TicketImpl
 * @see Ticket
 * @generated
 */
public abstract class TicketBaseImpl extends TicketModelImpl implements Ticket {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ticket model instance should use the <code>Ticket</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TicketLocalServiceUtil.addTicket(this);
		}
		else {
			TicketLocalServiceUtil.updateTicket(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-652041425